name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            ðŸ‘‹ @{{ author }}
            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.
            
            Please keep in mind these instructions.
            
            - [x] Create an issue for making any changes to the code. When the issue is approved you can make changes.
            - [x] Pull the latest change from an upstream branch before starting the changing of code.
            - [x] Add your file to a properly named directory (lowercase) 
            - [x] Use Flake8 locally for linting Python Code. - `pip install flake8`    
            - [x] Add pytest/unit test if possible
            - [x] Add README.md for your script instructions to run the script with the required dependencies.
            - [x] Script should be in plugin format. (if possible, it will be great)
            
            Please Read Once the [CONTRIBUTING](https://github.com/codePerfectPlus/awesomeScripts/blob/master/CONTRIBUTING.md) Guidelines 
            for further instructions. 
  
